---
- name: Install and start Apache HTTP Server
  hosts: 44.204.227.188
  become: true
  
  tasks:
    - name: Install httpd package
      yum:
        name: httpd
        state: present

    - name: Start httpd service
      service:
        name: httpd
        state: started
        enabled: true
