---
- name: Deploy httpd
  hosts: 44.204.227.188
  become: true

  tasks:
    - name: Install apache web server
      yum:
        name: httpd
        state: present
    - name: Start the server
      systemd:
        name: httpd
        state: started
        enabled: yes
