name: Deploy to EC2 for Ansible Controller Execution test

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: [self-hosted, ansible-controller]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Echo command to verify the connection with EC2
        run: echo "Connected to EC2 asif Shaik on the Ansible controller"

      - name: Install dependencies
        run: sudo yum update -y && sudo amazon-linux-extras install ansible2

      - name: Run Ansible playbook
        run: ansible-playbook --version
      - name: Install and start Apache HTTP Server
        hosts: 44.204.227.188
        become: true
        tasks:
          - name: Install httpd package
            package:
              name: httpd
              state: present

          - name: Start httpd service
            service:
              name: httpd
              state: started


