name: Deploy to EC2 for Ansible Controller Execution test

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: [self-hosted, ansible-controller]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Echo command to verify the connection with EC2
        run: echo "Connected to EC2 asif Shaik on the Ansible controller"

      - name: Install dependencies
        run: sudo yum update -y && sudo amazon-linux-extras install ansible2

      - name: Run Ansible playbook
        run: ansible-playbook --version
      - name: Run Ansible playbook (with AWS support)
        # You may pin to the exact commit or the version.
        # uses: maurete/ansible-action@48e4301a78df1a4871d244d2740389cc6830e211
        uses: maurete/ansible-action@v2
        with:
          # Name of the playbook to execute.
          playbook: ../../test/test.yaml

