name: Deploy to EC2 for Ansible Controller Execution test

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: [self-hosted, ansible-controller]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Echo command to verify the connection with EC2
        run: echo "Connected to EC2 asif Shaik on the Ansible controller"  

      - name: Run Ansible playbook
        run: ansible-playbook -i 44.204.227.188, ../../apache-playbook/apache-install.yaml
